# Generated by Django 2.1 on 2018-11-01 06:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Eps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('nombre_servicio', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HistorialMedico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condicion', models.TextField()),
                ('alergias', models.CharField(max_length=140)),
                ('cirugias', models.CharField(max_length=140)),
                ('rh', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Itinerario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('tipo_cita', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PuntoAtencion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('horario', models.CharField(max_length=100)),
                ('eps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Odrivers.Eps')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duracion', models.DateTimeField()),
                ('herramientas', models.CharField(max_length=100)),
                ('hora_fin', models.DateTimeField()),
                ('hora_inicio', models.DateTimeField()),
                ('tipo_servicio', models.CharField(max_length=100)),
                ('eps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Odrivers.Eps')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.IntegerField()),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=120)),
                ('rol', models.CharField(max_length=100)),
                ('telefono', models.IntegerField()),
                ('fecha_nacimiento', models.DateField()),
                ('direccion', models.CharField(max_length=70)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='servicio',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Odrivers.Usuario'),
        ),
        migrations.AddField(
            model_name='itinerario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Odrivers.Usuario'),
        ),
        migrations.AddField(
            model_name='historialmedico',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Odrivers.Usuario'),
        ),
    ]
